import '/imports/api/communities/methods.js';
import '/imports/api/communities/publications.js';
import '/imports/api/parcels/methods.js';
import '/imports/api/parcels/publications.js';
//import '/imports/api/parcels/tables.js';
import '/imports/api/meters/methods.js';
import '/imports/api/meters/publications.js';
import '/imports/api/users/methods.js';
import '/imports/api/users/publications.js';
import '/imports/api/memberships/methods.js';
import '/imports/api/memberships/publications.js';
import '/imports/api/leaderships/methods.js';
import '/imports/api/leaderships/publications.js';
import '/imports/api/delegations/methods.js';
import '/imports/api/delegations/publications.js';
import '/imports/api/agendas/methods.js';
import '/imports/api/agendas/publications.js';
import '/imports/api/partners/methods.js';
import '/imports/api/partners/publications.js';
import '/imports/api/contracts/methods.js';
import '/imports/api/contracts/publications.js';
import '/imports/api/topics/methods.js';
import '/imports/api/topics/publications.js';
import '/imports/api/topics/votings/methods.js';
// import '/imports/api/topics/votings/publications.js';
import '/imports/api/topics/tickets/methods.js';
// import '/imports/api/topics/tickets/publications.js';
import '/imports/api/topics/rooms/methods.js';
import '/imports/api/topics/rooms/publications.js';
// import '/imports/api/topics/feedbacks/methods.js';
import '/imports/api/topics/feedbacks/publications.js';
import '/imports/api/comments/methods.js';
import '/imports/api/transactions/methods.js';
import '/imports/api/transactions/publications.js';
import '/imports/api/transactions/breakdowns/methods.js';
import '/imports/api/transactions/breakdowns/publications.js';
import '/imports/api/transactions/tx-cats/methods.js';
import '/imports/api/transactions/tx-cats/publications.js';
import '/imports/api/transactions/balances/methods.js';
import '/imports/api/transactions/balances/publications.js';
// import '/imports/api/transactions/bills/methods.js';
import '/imports/api/transactions/bills/publications.js';
// import '/imports/api/transactions/payments/methods.js';
import '/imports/api/transactions/payments/publications.js';
import '/imports/api/transactions/parcel-billings/methods.js';
import '/imports/api/transactions/parcel-billings/publications.js';
import '/imports/api/transactions/statements/methods.js';
import '/imports/api/transactions/statements/publications.js';
import '/imports/api/transactions/statement-entries/methods.js';
import '/imports/api/transactions/statement-entries/publications.js';
import '/imports/api/permissions/publications.js';
import '/imports/api/shareddocs/publications.js';
import '/imports/api/shareddocs/methods.js';
import '/imports/api/shareddocs/sharedfolders/publications.js';
import '/imports/api/shareddocs/sharedfolders/methods.js';
