import '/imports/api/communities/methods.js';
import '/imports/api/communities/publications.js';
import '/imports/api/parcels/methods.js';
import '/imports/api/parcels/publications.js';
import '/imports/api/users/methods.js';
import '/imports/api/users/publications.js';
import '/imports/api/memberships/methods.js';
import '/imports/api/memberships/publications.js';
import '/imports/api/delegations/methods.js';
import '/imports/api/delegations/publications.js';
import '/imports/api/agendas/methods.js';
import '/imports/api/agendas/publications.js';
import '/imports/api/topics/methods.js';
import '/imports/api/topics/publications.js';
import '/imports/api/topics/votings/methods.js';
// import '/imports/api/topics/votings/publications.js';
import '/imports/api/topics/tickets/methods.js';
// import '/imports/api/topics/tickets/publications.js';
import '/imports/api/topics/rooms/methods.js';
import '/imports/api/topics/rooms/publications.js';
// import '/imports/api/topics/feedbacks/methods.js';
import '/imports/api/topics/feedbacks/publications.js';
import '/imports/api/comments/methods.js';
import '/imports/api/comments/publications.js';
import '/imports/api/transactions/breakdowns/methods.js';
import '/imports/api/transactions/breakdowns/publications.js';
import '/imports/api/transactions/txdefs/methods.js';
import '/imports/api/transactions/txdefs/publications.js';
import '/imports/api/transactions/balances/publications.js';
import '/imports/api/transactions/methods.js';
import '/imports/api/transactions/publications.js';
import '/imports/api/permissions/publications.js';
import '/imports/api/shareddocs/publications.js';
import '/imports/api/shareddocs/methods.js';
import '/imports/api/shareddocs/sharedfolders/publications.js';
import '/imports/api/shareddocs/sharedfolders/methods.js';
